# Generated by Django 3.2.5 on 2021-08-05 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='samplemodel',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='samplemodel',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
    ]
