# Generated by Django 3.2.5 on 2021-08-06 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210805_0624'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='samplemodel',
            options={'ordering': ['-title']},
        ),
        migrations.AddField(
            model_name='samplemodel',
            name='year',
            field=models.DateField(blank=True, null=True),
        ),
    ]
