# Generated by Django 3.2.5 on 2021-08-09 15:33

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210806_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='samplemodel',
            name='details',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
